services:
  # --- RABBITMQ INSTANCES ---
  rabbitmq_user:
    image: rabbitmq:3.11-management
    container_name: rabbitmq_user
    ports:
      - "5673:5672"
      - "15673:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  rabbitmq_card:
    image: rabbitmq:3.11-management
    container_name: rabbitmq_card
    ports:
      - "5674:5672"
      - "15674:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  # --- MYSQL INSTANCES ---
  mysql_user:
    image: mysql:8.0
    container_name: mysql_user
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: users_db
    ports:
      - "3307:3306"
    volumes:
      - ./mysql_user_init:/docker-entrypoint-initdb.d

  mysql_card:
    image: mysql:8.0
    container_name: mysql_card
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: cards_db
    ports:
      - "3308:3306"
    volumes:
      - ./mysql_card_init:/docker-entrypoint-initdb.d

  # # --- PYTHON WORKERS ---
  # service_user:
  #   build: ./service_user
  #   container_name: service_user
  #   depends_on:
  #     - rabbitmq_user
  #     - mysql_user
  #     - rabbitmq_card
  #   environment:
  #     LOCAL_RABBIT_HOST: rabbitmq_user
  #     LOCAL_RABBIT_PORT: 5672
  #     REMOTE_RABBIT_HOST: rabbitmq_card
  #     REMOTE_RABBIT_PORT: 5672
  #     RABBIT_USER: guest
  #     RABBIT_PASS: guest
  #     MYSQL_HOST: mysql_user
  #     MYSQL_PORT: 3306
  #     MYSQL_USER: root
  #     MYSQL_PASS: rootpass
  #     MYSQL_DB: users_db

  # service_card:
  #   build: ./service_card
  #   container_name: service_card
  #   depends_on:
  #     - rabbitmq_card
  #     - mysql_card
  #     - rabbitmq_user
  #   environment:
  #     LOCAL_RABBIT_HOST: rabbitmq_card
  #     LOCAL_RABBIT_PORT: 5672
  #     REMOTE_RABBIT_HOST: rabbitmq_user
  #     REMOTE_RABBIT_PORT: 5672
  #     RABBIT_USER: guest
  #     RABBIT_PASS: guest
  #     MYSQL_HOST: mysql_card
  #     MYSQL_PORT: 3306
  #     MYSQL_USER: root
  #     MYSQL_PASS: rootpass
  #     MYSQL_DB: cards_db
